### ISSUE TITLE
Make run no longer works due to changing REAME.md -> README.rst

### ISSUE THREAD

**Issue by dshirley** [Runscope/httpbin#200]
Here's the error:
    cat README.md|sed 's/(http:\/\/httpbin.org\//(\//'|ronn -5 -f --style 80c --pipe > ./httpbin/templates/httpbin.1.html
    cat: README.md: No such file or directory

I tried fixing the error by updating the Makefile to use "README.rst" instead, however, the html that was produced was pretty bad looking.

**Comment by msabramo** [comment]
There has been discussion of removing the ronn stuff in #97. 

Time to do it perhaps?

**Comment by dshirley** [comment]
Fine by me.  I had thoughts that it would potentially be helpful to have a few setup instructions in the README (a list of prerequisites, how to get pip, run pip, etc).  I have some notes on what I had to do to get up and running.  If you think it would be helpful, I'm happy to create a PR.

**Comment by sigmavirus24** [comment]
Getting and running pip is already well covered by things like [The Hitchhiker's Guide to Python](python-guide.org). I'm generally adverse to adding that level of detail to any project personally. If there are other notes, feel free to send a PR about them.

**Comment by sigmavirus24** [comment]
Perhaps we should deprecate use of `make run`.

**Comment by msabramo** [comment]
I agree @sigmavirus24 though I think deprecating `make html` is even more important.

**Comment by msabramo** [comment]
Oops I just deleted `Makefile`. Was thinking it would send a PR; forgot I have commit. 

I can put it back if there are objections.

**Comment by sigmavirus24** [comment]
In my humble opinion, nothing of great value was lost.

**Comment by dshirley** [comment]
> Getting and running pip is already well covered by things like The Hitchhiker's Guide to Python. I'm generally adverse to adding that level of detail to any project personally. If there are other notes, feel free to send a PR about them.

My notes were the following:
    gem install ronn foreman
    sudo easy_install pip
    sudo pip install -r requirements.txt

However, since the Makefile was removed, the first command is no longer needed.  I also just realized that running "pip install requirements.txt" is already mentioned in the README (I must have missed that before).  Having addressed those considerations, I think the docs are sufficient.

**Comment by kevin1024** [comment]
:+1: for removing Ronn; it always was a little fiddly and we don't necessarily want the content of index.html to match the README.
