### ISSUE TITLE
Some HTTPS Feature Requests

### ISSUE THREAD

**Issue by sigmavirus24** [Runscope/httpbin#213]
I was sitting in @ashfall and @radix's talk at PyTennessee and we discussed adding subdomains or other configurations to httpbin to give people ways to test how clients handle some of the less common corner cases around HTTPS.

Some ideas we had:

- Invalid certificates
  - Hostname mismatch
  - Expired certificate
- Self-signed certificate (no trust chain)

And I'm forgetting the other things. Hopefully they'll help flesh these out and @Runscope/owners can help us figure out what's possible.

**Comment by johnsheehan** [comment]
We've had similar ideas, but probably at something like tlsbin.org

**Comment by sigmavirus24** [comment]
Yeah! tlsbin makes sense. I wonder if the following also makes sense for features on tlsbin:

- A subdomain that supports at best TLSv1.0

  The reason being that sometimes the protocols that a client supports are not well documented so having a way to test if your client will support SSLv2/SSLv3 would be convenient. A response from this subdomain could probably at least list the protocols and ciphers that client supports.

- A subdomain that does not support either SSLv{2,3} and only TLSv1.0+.

I think a generic `GET /detect HTTP/1.1` to tlsbin.org which returns as much information as it can about the client's capabilities and the negotiated protocol/cipher could be simultaneously helpful and redundant. There's already https://www.howsmyssl.com/ but that generally just grades you and gives you similar information about what your client supports.

Thoughts?

**Comment by radix** [comment]
Other things:
- revoked certs
- subdomains that use SNI (maybe all of these domains will use SNI, but specifically users should have a way to know that their client is doing SNI correctly)
- also, maybe servers that only support SSL2 or SSL3 so people can test their clients *won't* be downgraded to those

especially when it comes to proto versions and cipher suites, we could spend all day adding to the feature list, but obviously we have to stop at some point.

**Comment by johnsheehan** [comment]
https://badssl.com covers a bunch of these and I think it's out of scope for httpbin so I'm going to close this issue.

**Comment by sigmavirus24** [comment]
:+1: Yeah, this was never meant to be implemented in httpbin. It just seemed to be a good related project to brainstorm on. Cheers!
