### ISSUE TITLE
adding /date api

### ISSUE THREAD

**Issue by Jxck** [Runscope/httpbin#214]
/date api for getting result of date (like result of date command) seems useful for me.

like
- /date/:timezone

```
$ curl http://httpbin.org/date/UTC-8
{
    "date": "Wed Feb 18 07:53:43 PST 2015"
}

$ curl http://htttpbin.rog/date # default UTC+0
```

how about this feature request ?

**Comment by sigmavirus24** [comment]
I don't see the usefulness of this. How is this something that should be included in a service used for testing HTTP clients? 
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by johnsheehan** [comment]
Can you explain more how clients might use this? Without compelling evidence for use cases, I'd be against adding this feature.
