### ISSUE TITLE
JSON output gets reordered

### ISSUE THREAD

**Issue by jeroenooms** [Runscope/httpbin#217]
I noticed that JSON objects that are posted to httpbin get reordered alphabetically in the json output. I know that json maps are technically unordered so this is not incorrect per se, but given that httpbin is frequently used for testing clients, it can be surprising that the data gets altered.

For example see below. In the input, the `foo` key appears first, whereas in the output the `bar` key appears first. 

```bash
curl http://httpbin.org/post -d '[{"foo" : 123, "bar" : 456}]' -H "Content-Type: application/json"
```

```json
{
  "args": {}, 
  "data": "[{\"foo\" : 123, \"bar\" : 456}]", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Content-Length": "28", 
    "Content-Type": "application/json", 
    "Host": "httpbin.org", 
    "User-Agent": "curl/7.37.1"
  }, 
  "json": [
    {
      "bar": 456, 
      "foo": 123
    }
  ], 
  "origin": "167.220.26.164", 
  "url": "http://httpbin.org/post"
}
```

**Comment by sigmavirus24** [comment]
Objects in JSON are not inherently ordered so there is no reason that HTTPbin should have any obligation to preserve ordering provided to it. See: 

- http://json.org/

> An object is an unordered set of name/value pairs. An object begins with { (left brace) and ends with } (right brace). Each name is followed by : (colon) and the name/value pairs are separated by , (comma).

- https://tools.ietf.org/html/rfc7159#section-1

> An object is an unordered collection of zero or more name/value
> pairs, where a name is a string and a value is a string, number,
> boolean, null, object, or array.

**Comment by jeroenooms** [comment]
Yes I know that, it was mentioned in the post. It's just unexpected and makes it harder to write simple unit tests with httpbin.

**Comment by johnsheehan** [comment]
I'm curious to learn more about your tests. Why do they rely on attribute order?






On Sat, Feb 28, 2015 at 6:55 PM -0800, "Jeroen Ooms" <notifications@github.com> wrote:












Yes I know that, it was mentioned in the post. It's just unexpected and makes it harder to write simple unit tests with httpbin.

**Comment by sigmavirus24** [comment]
Just to make sure no one missed this, @jeroenooms you do realize that the `data` attribute has your data as it was serialized and therefore in the order you expect it to be.
