### ISSUE TITLE
Adding a 'random-delay' endpoint

### ISSUE THREAD

**Issue by elbaschid** [Runscope/httpbin#227]
First of all, great work everyone. I like the work that you've done!

I've just been looking into handling random timeouts on an external service and couldn't find an endpoint on httpbin that would return a response with a "random" delay. I was wondering if that's something that would be useful to add, either as an additional endpoint or as a query parameter to the `/delay/n` endpoint? 

My experiment is in this gist: https://gist.github.com/elbaschid/e8baf68b4a0f6ea27440 which hopefully makes enough sense. 

I'm happy to create a PR for this but wanted to check first if this is considered to be in scope and what the API should look like.

**Comment by sigmavirus24** [comment]
Since you can specify the delay value, why not do something like:

```py
import random

delay = random.randint(0, 5)
delayed_url = 'https://httpbin.org/delay/%d' % delay
# request that URL
```

It has the same effect and is something that you'll be able to use today.

**Comment by johnsheehan** [comment]
I'm with @sigmavirus24 on this one. Less code to do it from the calling side then to add it

**Comment by elbaschid** [comment]
If I'm not mistaken, that wouldn't work for my use case, since I am requesting the same URL but expect the delay to be different on every request, to experiment with the retry feature in requests.

But I see both your points that this might be too much code for a very rare use case. Feel free to close it. I just thought it's worth asking :smile:

**Comment by sigmavirus24** [comment]
It was worth asking! I think what @johnsheehan and I are considering though is the idea that httpbin should be able to encompass the 98% use case and this doesn't seem like one of those use cases. I'm pretty sure if this was something that would see more use, we'd be happy to add it. Thanks for thinking of us though!

**Comment by adabuleanu** [comment]
I think this is a useful feature. I was looking into testing the [retry mechanisms inside istio](https://istio.io/latest/docs/concepts/traffic-management/#retries) for an  external service (e.g. httpbin.org) . This is a [good article](https://piotrminkowski.com/2020/06/03/circuit-breaker-and-retries-on-kubernetes-with-istio-and-spring-boot/) on how to achieve this, but unfortunately there is no feature for random delays.  Please reconsider adding this feature. thx
