### ISSUE TITLE
Connection header in Google Chrome browser

### ISSUE THREAD

**Issue by smarts** [Runscope/httpbin#237]
Google Chrome says it's sending `Connection: keep-alive` but I don't see it echoed in the response.

**Comment by sigmavirus24** [comment]
It's very likely that Heroku's proxy is eating this. It eats other headers as well. See #231 for more details.

Please attempt to reproduce this with a local running instance of HTTPbin and let me know what you find.

**Comment by darrelmiller** [comment]
Connection is by definition a per hop directive.  Therefore it only affects the connection between the client and the next intermediary.  It [MUST](https://tools.ietf.org/html/rfc7230#section-6.1) not re-transmitted by the intermediary. 
At is also a redundant header if you are using HTTP/1.1.  Persistent connections are used by default in HTTP/1.1.  The HTTP 1.1 spec does not even define keep-alive anymore, in fact it warns against using it https://tools.ietf.org/html/rfc7230#appendix-A.1.2

**Comment by smarts** [comment]
Fair enough. Feel free to close the issue and label it as a duplicate of the other. I recommend adding some sort of section to the readme file since it's an issue that's likely to come up again. Thanks for the quick response!

**Comment by sigmavirus24** [comment]
@darrelmiller :cake:
