### ISSUE TITLE
Tracking scripts in httpbin package on PyPI

### ISSUE THREAD

**Issue by The-Compiler** [Runscope/httpbin#245]
It seems the package released to PyPI contains tracking beacons for Google Analytics and perfectaudience.com

I can see that being useful for httpbin.org (even though I'd prefer another service than Google Analytics, but whatever) - but I really think the version released to PyPI (which could get used e.g. for running it via a CI for some kind of tests) should come without those.

**Comment by johnsheehan** [comment]
I can't recall who's maintaining the PyPI version but if anyone wants to add support for excluding those scripts in that version, I'm all for it.

**Comment by The-Compiler** [comment]
From the PyPI page:

```
Package Index Owner: runscopejohn, kevin1024, kennethreitz
Package Index Maintainer: kevin1024
```

/cc @kevin1024

**Comment by The-Compiler** [comment]
What about using an environment variable to control the inclusion of those trackers? There's already `BUGSNAG_API_KEY` to report exceptions (which I'm guessing is used with the httpbin.org instance), so why not have something like `ENABLE_TRACKING` in the environment as well, and don't include `trackingscripts.html` in `index.html` if it's unset?

**Comment by johnsheehan** [comment]
Sounds like a good plan to me

**Comment by kevin1024** [comment]
Yup, sounds good to me too.  So I guess when we build the package, we just have to remember to set the environment variable?  Or we can probably have `setup.py` automatically set it for us?

**Comment by johnsheehan** [comment]
Make the default false if the setting doesn't exist and we'll take care of making sure it's set to true for httpbin.org






On Mon, Aug 31, 2015 at 11:22 AM -0700, "Kevin McCarthy" <notifications@github.com> wrote:












Yup, sounds good to me too.  So I guess when we build the package, we just have to remember to set the environment variable?  Or we can probably have setup.py automatically set it for us?

**Comment by The-Compiler** [comment]
@kevin1024 It'd be a runtime option, not a build-time option

**Comment by kevin1024** [comment]
> It'd be a runtime option, not a build-time option

Ah ok yeah, that's better.

**Comment by kevin1024** [comment]
Well, I'm happy to build/push a new package to pypi if you add the env variable in a PR @The-Compiler

**Comment by The-Compiler** [comment]
Awesome - working on it!

**Comment by The-Compiler** [comment]
There we go: #246 :smile:
