### ISSUE TITLE
Start httpbin server in background

### ISSUE THREAD

**Issue by gsouf** [Runscope/httpbin#257]
I did set httpbin for my unit tests.

I'm following the readme and use gunicorn to start the application but I had to use some ugly workaround to get it working as expected. See my bash script for starting tests: 

```bash
gunicorn httpbin:app &  # need to use & to run it in background

sleep 2 # Without that it was failling because test were beginning before server was started

## Run unit test
...
...

pkill gunicorn # Couldnt find other way to stop the application.
```

Is there a way to start the application properly in the background and how to stop it ?

**Comment by kevin1024** [comment]
If you're using pytest, check out my project [pytest-httpbin](https://github.com/kevin1024/pytest-httpbin)

If not, check out the note in the readme about how to use it with unittest, then run your tests with pytest :)

Otherwise, check out the implementation to see how it's done.
