### ISSUE TITLE
[feature] get - add a qs param (such as: body) to specify response data

### ISSUE THREAD

**Issue by haoxins** [Runscope/httpbin#263]
such as

```
GET ?body=foo
```

will get a response with body content `foo`

If this is acceptable, I can submit a **PR**

**Comment by sigmavirus24** [comment]
```
$ http GET https://httpbin.org/get?foo=bar
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 258
Content-Type: application/json
Date: Wed, 18 Nov 2015 01:43:51 GMT
Server: nginx

{
    "args": {
        "foo": "bar"
    },
    "headers": {
        "Accept": "*/*",
        "Accept-Encoding": "gzip, deflate",
        "Host": "httpbin.org",
        "User-Agent": "HTTPie/0.9.2"
    },
    "origin": "72.160.201.233",
    "url": "https://httpbin.org/get?foo=bar"
}
```

It's already there in the form of `args`.

**Comment by coderhaoxin** [comment]
@sigmavirus24

I mean

```bash
$ http GET https://httpbin.org/get?body=foo
HTTP/1.1 200 OK

some headers

foo
```

the response body is `foo`

This will be useful for some use cases.

**Comment by haoxins** [comment]
@sigmavirus24

I mean

```bash
$ http GET https://httpbin.org/get?body=foo
HTTP/1.1 200 OK

some headers

foo
```

the response body is `foo`

This will be useful for some use cases.

**Comment by johnsheehan** [comment]
I think something like mocky.io or mockable.io is better for something like this.






On Tue, Nov 17, 2015 at 8:35 PM -0800, "haoxin" <notifications@github.com> wrote:












@sigmavirus24



I mean

$ http GET https://httpbin.org/get?body=foo
HTTP/1.1 200 OK

some headers

foo



the response body is foo



This will be useful for some use cases.
