### ISSUE TITLE
Fix build in ASCII locale

### ISSUE THREAD

**Issue by 0-wiz-0** [Runscope/httpbin#269]
When building in an ASCII locale, setup.py fails with:
````
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    os.path.join(os.path.dirname(__file__), 'README.rst')).read()
  File "/usr/pkg/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2313: ordinal not in range(128)
````
The easy fix is to replace two dashes in README.rst with '-' or '--'. I can send a PR if wanted.
After changing that, the build succeeds without further problems.

**Comment by sigmavirus24** [comment]
@0-wiz-0 feel free to send a PR updating that to -.

**Comment by 0-wiz-0** [comment]
Done: https://github.com/Runscope/httpbin/pull/270
