### ISSUE TITLE
Plaintext IP endpoint

### ISSUE THREAD

**Issue by rgtk** [Runscope/httpbin#274]
Plaintext IP endpoint would be really helpful especially in scripts.

    $ curl http://httpbin.org/ip.txt --proxy $PROXY >> ips.txt

**Comment by sigmavirus24** [comment]
That should just be content negotiation, e.g., sending `Accept: text/plain` as a header but I'm not sure we actually want this. There are lots of other services that already do things like this.

Further you could use `jq` to select the `origin` attribute from the response and only print that out.

**Comment by rgtk** [comment]
Sending headers via `curl` require more typing, and we all know shell is for getting things done fast. Installing addtional programs for this is overkill, in my opinion.

**Comment by johnsheehan** [comment]
http://ifconfig.co/
