### ISSUE TITLE
Please upload latest version to pypi

### ISSUE THREAD

**Issue by neb14** [Runscope/httpbin#275]
I really need the float seconds on delay

**Comment by sigmavirus24** [comment]
I'll take care of this tonight unless someone beats me to it.

**Comment by sigmavirus24** [comment]
If someone does beat me to it, *please* tag the release. Our last released version is 0.1.x and we're missing tags for the other intermediary versions.

**Comment by sigmavirus24** [comment]
0.4.1 is up on PyPI. Also all the intermediate versions have been tagged in the repo.

**Comment by neb14** [comment]
Thanks

Ben

Please pardon any typos; Sent from my phone

On Jan 27, 2016, at 10:06 AM, Ian Cordasco <notifications@github.com> wrote:

0.4.1 is up on PyPI. Also all the intermediate versions have been tagged in
the repo.

—
Reply to this email directly or view it on GitHub
<https://github.com/Runscope/httpbin/issues/275#issuecomment-175712710>.
