### ISSUE TITLE
How to use basic digest authentication with httpbin?

### ISSUE THREAD

**Issue by martinda** [Runscope/httpbin#277]
Whenever I hit the http://httpbin.org/basic-auth/user/passwd link, I am prompted to enter a username and a password, but no matter what I type, it keeps prompting me back. How is this link supposed to work?

**Comment by martinda** [comment]
Forget it, I figured it out. The user name and password are "user" and "passwd", they match what comes after `/basic-auth/`.

**Comment by kennethreitz** [comment]
FYI, that's not digest authentication :)
