### ISSUE TITLE
Allow for setting status code and method in /redirect and /redirect-to

### ISSUE THREAD

**Issue by tzickel** [Runscope/httpbin#283]
Currently the redirect is limited to GET and returning 302. I discovered a bug in requests which uses httpbin for it's server in the test suite. The bug requires both that the redirect be non-GET and redirect with 307 and not 302 (so the method is preserved).

https://github.com/kennethreitz/requests/issues/3079

I think like redirect-to has an url parameter, it should have an status-code parameter as well.

**Comment by sigmavirus24** [comment]
Fixed in #284 I believe
