### ISSUE TITLE
SSL/TLS test cases

### ISSUE THREAD

**Issue by JensRantil** [Runscope/httpbin#286]
Something really useful would be to support various SSL/TLS test cases that should fail:
 * "Common Name" not matching "Hostname".
 * Missing intermediate certificate.
 * Self-signed certificate.

This would be really useful when one is testing how an HTTP library reacts to these corner cases. Similar to https://www.tls-o-matic.com.

**Comment by The-Compiler** [comment]
I agree - https://badssl.com/ ([source](https://github.com/google/badssl.com)) also has some useful tests.

**Comment by sigmavirus24** [comment]
So local httpbin would not be able to support any of these use-cases. Runscope has expressed disinterest in supporting this on httpbin.org. Finally, there are already several sites (as you both have noted) that support these use-cases better than we could. See also #213.
