### ISSUE TITLE
Would it be possible to add a "/timeout" endpoint to httpbin?

### ISSUE THREAD

**Issue by samphippen** [Runscope/httpbin#291]
My use case is building a client that understands the unreliability of distributed systems, and attempts backoffs, retries and other stuff. Having an endpoint which intentionally never returns a response or similarly represents the unreliability here would be really useful. Let me know if I can provide more detail.

**Comment by sigmavirus24** [comment]
So `/delay/:n` can do that, but I think it only let's you delay for 10 seconds at most. It absolutely returns a response, but I'm not sure we want an endpoint that doesn't ever return a response.

**Comment by johnsheehan** [comment]
This could potentially tie up too many resources and effect the performance of the site.






On Thu, Jun 16, 2016 at 6:23 AM -0500, "Ian Cordasco" <notifications@github.com> wrote:












So /delay/:n can do that, but I think it only let's you delay for 10 seconds at most. It absolutely returns a response, but I'm not sure we want an endpoint that doesn't ever return a response.

**Comment by sigmavirus24** [comment]
> This could potentially tie up too many resources and effect the performance of the site.

Right. I suppose we could attempt to add an endpoint that just randomly closes the connection, but that's hard to do in plain flask. :/ Sorry @samphippen
