### ISSUE TITLE
Stream endpoints are not really streaming?

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Runscope/httpbin#295]
When I query `/stream` or `/drip` endpoints with `curl --no-buffer`, all the output appears at once (instead of being streamed to my console over time). 

It appears like there is some buffering in the backend.

**Comment by ahmetalpbalkan** [comment]
I confirmed this by building a server with streaming+flushing in Go and using `curl --no-buffer`. It worked just fine. It appears like httpbin is doing either buffering or has flushing issues.

**Comment by johnsheehan** [comment]
We run httpbin behind nginx which by default buffers responses from the proxied host. We have turned that off for these endpoints. Can you try again and verify that it's working for you now?

**Comment by ahmetalpbalkan** [comment]
@johnsheehan `/drip` works correctly now, I can see it happening.

`/stream` still prints everything at once, is that expected?

**Comment by johnsheehan** [comment]
I think it's just happening so fast you can't tell that it's actually streaming instead of buffering. If someone wants to contribute something to add delays between /stream chunks we can consider that in another issue.
