### ISSUE TITLE
Include X-Forwarded-For header in headers section

### ISSUE THREAD

**Issue by Antoniossss** [Runscope/httpbin#300]
Looks like X-Forwarded-For header is stripped from the headers collecion. I know, that its value is shown as entry in origin field, but for straight clarity from where this information came from, header should be included in headers sections as well.

I have just noticed that in curl examples X-Forwarded-For is included in headers section. I guess this must have change in a meantime.

**Comment by Antoniossss** [comment]
My bad, adding ?show_env=1 does the trick...

**Comment by alexfornuto** [comment]
> My bad, adding ?show_env=1 does the trick...

FWIW, I don't consider this "your bad". It's 5 years later, and that comment is how I solved this for myself, not knowing that such a parameter would be needed. In other words, thanks for adding documentation for this "feature"!

**Comment by chrissound** [comment]
Surely this should be enabled by default?

**Comment by simonqbz** [comment]
8 years later and luckily I stumbled on this issue. When I do a call to /headers I was expecting to see ALL headers, but X-Forwarded-For and X-Forwarded-Proto were stripped.  And the only thing I installed httpbin was that I wanted to see if these specific headers were being added, go figure:)
Thanks @Antoniossss !

**Comment by dnelen** [comment]
@Antoniossss thank you!
