### ISSUE TITLE
general chunked response question

### ISSUE THREAD

**Issue by woosley** [Runscope/httpbin#301]
I am looking into getting chunked response using httpbin /stream/10,  it seems that Transfer-Encoding is not sent in the response header, and the question is: how is the body sent?

I am looking for something like what https://en.wikipedia.org/wiki/Chunked_transfer_encoding#Encoded_data said, the response should contain the size of each chunk,  but httpbin does not seem to be sending the size?

**Comment by MarloweW** [comment]
It is set. 

![image](https://cloud.githubusercontent.com/assets/9361073/18808187/f90eadac-828d-11e6-80b5-89957a77d122.png)

**Comment by sigmavirus24** [comment]
Thank you @MarloweW 

@woosley, I'm sorry I didn't respond sooner. The last ~1 month of my life has been hectic to say the least. :-) I'm afraid I can't help you without more information though. We can reopen this if you can help me reproduce what you're seeing.

**Comment by woosley** [comment]
I ran the httpbin with the builtin server and used httpie to see the details.

```
python -m httpbin.core --port 8080
 * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
127.0.0.1 - - [25/Sep/2016 09:34:52] "GET /stream/10 HTTP/1.1" 200 -

```
it does not seem to have the chunked header

```
http -v GET http://localhost:8080/stream/10
GET /stream/10 HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:8080
User-Agent: HTTPie/0.9.2



HTTP/1.0 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Connection: close
Content-Type: application/json
Date: Sun, 25 Sep 2016 01:34:52 GMT
Server: Werkzeug/0.10.4 Python/2.7.10
```

this might be a issue with Werkzeug?

**Comment by sigmavirus24** [comment]
So HTTPbin is *typically* run via Gunicorn (e.g., `pip install gunicorn; gunicorn httpbin:app`). This will get you the correct TE. For some reason, Werkzeug doesn't do that though if you run it the way you ran it.

You should file a bug against Flask (and then they might tell you to file it against Werkzeug).
