### ISSUE TITLE
HTTP/2 mirror

### ISSUE THREAD

**Issue by jeroenooms** [Runscope/httpbin#302]
It would be super nice to have a mirror which supports HTTP/2 to test multiplexing capabilities of clients.

**Comment by johnsheehan** [comment]
http2bin.org






On Wed, Sep 28, 2016 at 9:28 AM -0500, "Jeroen Ooms" <notifications@github.com> wrote:












It would be super nice to have a mirror which supports HTTP/2 to test multiplexing capabilities of clients.

**Comment by sigmavirus24** [comment]
Exactly. As @johnsheehan mentions, there is http://http2bin.org/ which is run behind h2o.

**Comment by jeroenooms** [comment]
OMG I wish I knew this sooner. Can you please advertise this on the httpbin.org homepage?

**Comment by sigmavirus24** [comment]
@jeroenooms send a pr to add it there?

**Comment by jeroenooms** [comment]
@sigmavirus24 OK here you go https://github.com/Runscope/httpbin/pull/303
