### ISSUE TITLE
Is there anyway to make the links relative?

### ISSUE THREAD

**Issue by polds** [Runscope/httpbin#310]
I'm wondering if there is anyway to make the links relative on the main page. We're wanting to host httpbin inside of a "folder" at www.example.com/httpbin which is behind HAProxy. We have this part working but all of the links are absolute so even though httpbin is running at www.example.com/httpbin/ the links point to www.example.com/get.

Wondering if there is any easy way of making all the links relative.

**Comment by sigmavirus24** [comment]
Do you mean the links when you view `www.example.com/httpbin/` in your browser?

If you look at the source https://github.com/Runscope/httpbin/blob/master/httpbin/templates/httpbin.1.html#L8, you can see we're not hard-coding these, we're using Flask's `url_for` helper. Frankly, I don't know how to make it do what you want or if it's possible.

**Comment by polds** [comment]
That points me in the right direction, thank you. I'll respond back if I find anything for the future curious.
