### ISSUE TITLE
"Connection: close" header not returned in /get json response.

### ISSUE THREAD

**Issue by divinity76** [Runscope/httpbin#313]
request generated with the code
```
$CrLf="\r\n";
$request=implode($CrLf,array(
		'GET /get HTTP/1.0',
		'Host: httpbin.org',
		'Connection: close'
)).$CrLf.$CrLf;
```

returns
```
�#HTTP/1.1 200 OK
Server: nginx
Date: Tue, 13 Dec 2016 09:33:38 GMT
Content-Type: application/json
Content-Length: 131
Connection: close
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true

{
  "args": {}, 
  "headers": {
    "Host": "httpbin.org"
  }, 
  "origin": "186.125.180.27", 
  "url": "http://httpbin.org/get"
}
```

on a side note, the `Host: httpbin.org`  header is _REQUIRED_ , which is annoying (did we run out of ipv4 addresses?), but i guess that should go in another issue

**Comment by sigmavirus24** [comment]
Hi @divinity76,

Are you using the hosted HTTPbin service or are you running it locally?

**Comment by divinity76** [comment]
the hosted httpbin.org/get , at ip 23.22.14.18

**Comment by sigmavirus24** [comment]
@divinity76 I suspect httpbin the app never actually sees that header. It's being served by nginx and I'd be unsurprised if nginx strips that header before it can reach httpbin the app. That's not a bug in httpbin.

I'd also be surprised if anyone at Runscope maintaining this infrastructure considers this a bug either.

**Comment by johnsheehan** [comment]
Correct. We don't have any plans to change how connection headers are handled on httpbin.org. Also, the Host header will always be required as well.

**Comment by sigmavirus24** [comment]
> Also, the Host header will always be required as well.

I wasn't going to touch that one @johnsheehan because of the fact that it's required by the HTTP/1.1 spec. =P
