### ISSUE TITLE
Support responding on arbitrary sub-paths?

### ISSUE THREAD

**Issue by cben** [Runscope/httpbin#315]
Not sure it's a desired use case for Httpbin, but I'm debugging a client library for a specific API.
(Sure, it won't successfully parse Httpbin responses, but it has a mode dumping responses, and that's good enough for my current purposes.)

If I tell the lib to use endpoint `http://httpbin.org/get`, it fails with 404 trying to access `http://httpbin.org/get/foo/bar`.
What if there was a way to tell endpoints to ignore the rest of the path?
E.g. I could use `http://httpbin.org/get/anyurl` as the base url, then `http://httpbin.org/get/anyurl/foo/bar` would work exactly like `http://httpbin.org/get` (except for `url: "http://httpbin.org/get/anyurl/foo/bar"` field).
Similarly for any endpoint with `/anyurl` appended.

I'll be happy to make a PR if this sounds useful.

**Comment by johnsheehan** [comment]
https://www.runscope.com/docs/debugging is a better fit for this if you're just looking for request introspection.






On Mon, Dec 26, 2016 at 10:42 AM -0600, "Beni Cherniavsky-Paskin" <notifications@github.com> wrote:












Not sure it's a desired use case for Httpbin, but I'm debugging a client library for a specific API.

(Sure, it won't successfully parse Httpbin responses, but it has a mode dumping responses, and that's good enough for my current purposes.)


If I tell it endpoint is http://httpbin.org/get it fails with 404 trying to access http://httpbin.org/get/foo/bar.

What if there was a way to tell endpoints to ignore the rest of the path?

E.g. I could use http://httpbin.org/get/anyurl as the base url, then http://httpbin.org/get/anyurl/foo/bar would work exactly like http://httpbin.org/get (except for url: "http://httpbin.org/get/anyurl/foo/bar" field).


I'll be happy to make a PR if this sounds useful.

**Comment by cben** [comment]
Yeah, sounds better.  Closing, ping me if anyone still wants me to make a PR.
