### ISSUE TITLE
HTTPS doesn't support required AES128-SHA cipher

### ISSUE THREAD

**Issue by tomlogic** [Runscope/httpbin#316]
I'm an embedded software developer, and a customer of ours had trouble testing our HTTPS client library with httpbin.org.  After troubleshooting the embedded client library I was able to confirm with openssl that it rejects connections using AES128-SHA:

```
$ openssl s_client -cipher 'AES128-SHA' -connect httpbin.org:443
CONNECTED(00000003)
140736082269192:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:741:
```

I saw the other issues with TLS-related requests, and accept that this isn't "tlsbin.org" but though it might be something worth investigating.  If it's possible to include details on the TLS connection in your JSON response, people might find that helpful as well.

**Comment by russau** [comment]
Hi @tomlogic,

Funny - I'm working on a pull request for exactly this! :)  You can see it running here: https://beta.twitterheatmap.com/tls

Or try something like:

````$ openssl s_client -connect beta.twitterheatmap.com:443````

Then send a:

````GET /tls````

Let me know if there's any features you'd want to go with this.  I plan on including some details about the cert that lives on the server, i.e. issuer, fingerprints, expiry dates.

Russ

**Comment by sigmavirus24** [comment]
It's not HTTPbin's job to support every cipher or TLS configuration. That would be quite difficult in fact. We've had discussions about TLS configuration on other issues and decided that those features belong in a different service that's dedicated to TLS rather than HTTP.

**Comment by russau** [comment]
@sigmavirus24 confirming - the feature you are closing is:

* AES128-SHA cipher
* my idea @ https://beta.twitterheatmap.com/tls
* both

I'm guessing both?

**Comment by tomlogic** [comment]
Can someone at least point me to the component responsible for configuring https?  I realize that @russau's work goes beyond your scope, but fixing your https server configuration to allow valid TLS 1.2 connections should still be of interest.  If not, maybe you should disable https access entirely and refer people to someone else's project.

**Comment by sigmavirus24** [comment]
@russau Closing the feature you're proposing.

@tomlogic For the hosted version of httpbin, you need the attention of Runscope's engineers who maintain the configuration. I suspect @johnsheehan can help you reach one of them. HTTPbin (the open source project) doesn't specify or mandate any particular cipher.
