### ISSUE TITLE
websockets support?

### ISSUE THREAD

**Issue by jordansissel** [Runscope/httpbin#42]
Yeah eh?  Maybe? :)

**Comment by tonyxiao** [comment]
heroku does now.

**Comment by sigmavirus24** [comment]
This is no longer hosted on heroku so it depends on @Runscope/httpbin and @Runscope/owners if they want to support this.

**Comment by srinivasreddy** [comment]
what is the status now?

**Comment by johnsheehan** [comment]
Not going to happen. httpbin will only support http for the foreseeable future.

**Comment by graingert** [comment]
@srinivasreddy FYI there's http://sockb.in/ now

**Comment by codeskyblue** [comment]
Found this one `wss://echo.websocket.org`  See demo <https://codepen.io/matt-west/pen/tHlBb>
