### ISSUE TITLE
Add support for file uploads

### ISSUE THREAD

**Issue by thefosk** [Runscope/httpbin#87]
It would be cool to add a `/post/upload` endpoint, which returns the file size of the uploaded object.

**Comment by nishanov** [comment]
Hi there. Any progress here?

**Comment by sigmavirus24** [comment]
Since this already exists, I'm inclined to close this unless there is some further clarification on why this needs to differ from `/post`.

**Comment by kennethreitz** [comment]
This is indeed what `/post` was intended for.

**Comment by moy** [comment]
It would be nice to have an `<input type="file">` on http://httpbin.org/forms/post, so that we can easily test the file upload from a form.

**Comment by iBasit** [comment]
no test upload?

**Comment by CMCDragonkai** [comment]
This assumes that the upload content type is a standard `multipart/form-data` or `application/x-www-form-urlencoded`. What if you are trying to upload all sorts of stuff like `application/x-tar`... etc?
